### ISSUE TITLE
Fix jumping to the top of the page after language change

### ISSUE THREAD

**Issue by marcol13** [akai-org/akai-code#42]
Steps to recreate:

1. Run page
2. Scroll down to one of the sections, e.g. **Registration**
3. Change language

Effect: website is scrolling up to the top

Expectation: website should be in the same place/section

**Comment by mlodyoskar** [comment]
Actually, I'm wondering whether it is unwanted behavior. I tested a couple of webpages with language change functionality, and most of them simply reload the page, but I found one where it doesn't: https://www.edgardcooper.com/de. 

But if we really think about it, if someone enters the page, automatically scroll down and want to change language, scroll to the top of the page is wanted behavior. Wdyt?

**Comment by marcol13** [comment]
Hmm, ok, maybe we do not need to do that as you said 😅 Scrolling up after language change seems to me a little weird, but if it's common behavior on websites with internalization, we can leave it as is 😉
